[package]
name = "getting-started"
version = "0.1.0"
edition = "2021"
author = "Haixuan Xavier Tao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
bytemuck = "1.7.2"
pollster = "0.2.4"